export const DEFAULTS = {
    BOID_COUNT: 500,
    PERCEPTION_RADIUS: 50,
    MAX_SPEED: 4,
    MAX_FORCE: 0.2,
    SEPARATION_WEIGHT: 1.5,
    ALIGNMENT_WEIGHT: 1.0,
    COHESION_WEIGHT: 1.0,
    TRAIL_LENGTH: 0,
    FRAME_RATE: 60,
    DRAG: 0.05,
    NOISE: 0.1,
    ALIGNMENT_BIAS: 1.0, // 1.0 = standard boids
};

export const CONSTRAINTS = {
    MIN_BOID_COUNT: 50,
    MAX_BOID_COUNT: 3000,
    MIN_PERCEPTION: 20,
    MAX_PERCEPTION: 200,
    MIN_SPEED: 1,
    MAX_SPEED: 15,
    MIN_DRAG: 0,
    MAX_DRAG: 0.1,
    MIN_NOISE: 0,
    MAX_NOISE: 0.5, // Radians
    MIN_BIAS: 0,
    MAX_BIAS: 4,
};
