export const DEFAULTS = {
    BOID_COUNT: 500,
    PERCEPTION_RADIUS: 50,
    MAX_SPEED: 4,
    MAX_FORCE: 0.2,
    SEPARATION_WEIGHT: 1.5,
    ALIGNMENT_WEIGHT: 1.0,
    COHESION_WEIGHT: 1.0,
    TRAIL_LENGTH: 0,
    FRAME_RATE: 60,
};

export const CONSTRAINTS = {
    MIN_BOID_COUNT: 50,
    MAX_BOID_COUNT: 3000,
    MIN_PERCEPTION: 20,
    MAX_PERCEPTION: 200,
    MIN_SPEED: 1,
    MAX_SPEED: 15,
};
